### ISSUE TITLE
Defender blocking core.ps1, fix breaks ability to update

### ISSUE THREAD

**Issue by TobiTenno** [Ash258/scoop#275]
- **Branch**:  main
- **Powershell Version**:  5.1.19041.1320

related to #216, but discussion there is closed.
on systems where one cannot add an exception for scoop/shovel (i.e. managed, corporate systems)

the fix described in #216 and https://github.com/ScoopInstaller/Scoop/issues/4097 work to fix it (removing Optimize-SecurityProtocol), however this causes scoop/shovel to be unable to update.

```ps
At C:\Users\USER\scoop\apps\scoop\current\lib\core.ps1:1 char:1
+ @(
+ ~~
This script contains malicious content and has been blocked by your antivirus software.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : ScriptContainedMaliciousContent
```

coprorate/managed system where I'm unable to add exceptions for shovel in defender.

**Comment by Ash258** [comment]
Use `NEW` branch or do not use Shovel when you are not allowed to use it.
