### ISSUE TITLE
Unable to Install Git when removing the "main" bucket

### ISSUE THREAD

**Issue by NatureHog** [Ash258/scoop#279]
- **Branch**: main
- **Powershell Version**: 5.1.22000.282

I wanted to change my scoop/shovel setup a bit, and I was stupid enough to remove the "main" bucket, because I thought the "Base" bucket is a mirror of the default "main" bucket. Additionally, I deleted Git, which makes it impossible to add the "main" bucket, and the "main" bucket being removed makes it impossible to download the git manifest. I do have the git manifest still in my /cache folder, though it doesn't seem to use it, and there's no command parameter to specifically use /cache...

I don't want to delete the entire /scoop folder, because I use scoop as much as I can, and it would be too much effort getting everything back to how I had it.

![image](https://user-images.githubusercontent.com/55314658/153917803-4263b861-47be-4755-a104-f4de95dbc69e.png)
Output of terminal
![image](https://user-images.githubusercontent.com/55314658/153920264-c5506120-03eb-4672-8195-0059e39a334e.png)
Contents of /cache

**Comment by Ash258** [comment]
```powershell
shovel config "lastupdate" "258|2023-02-14 10:00:32"
shovel install https://raw.githubusercontent.com/ScoopInstaller/Main/master/bucket/git.json --independent
shovel bucket add main
# Manualy edit scoop-install.json
Set-Content "$(shovel prefix git)\scoop-install.json" @"
{
    "architecture": "64bit",
    "bucket": "main"
}
"@
shovel update
```

**Comment by NatureHog** [comment]
Nope, still won't work.
I copied the install command from your answer, didn't change it, and it still gives the before mentioned error.
Even after the "lastupdate" config setting was changed to the mentioned value...

**Comment by Ash258** [comment]
Install manually NEW branch or apply this change: https://github.com/Ash258/Scoop-Core/commit/28bcb0cab95b3bf9abf8d46bf39abe866120bee1#diff-21c4dcc4de0731624550fef22715a9ce8b37c644357b5cda1f7ee68dd1637493R173-R179

```powershell
shovel config SCOOP_BRANCH NEW
$path1 = shovel prefix scoop
$path = $path1 | Split-Path -Parent
Rename-Item $path1 'old'
iwr -outfile "$path\zip.zip" 'https://github.com/Ash258/Scoop-Core/archive/refs/heads/NEW.zip'
7z x "$path\zip.zip" -o"$path"
Rename-Item "$path\Scoop-Core-NEW" 'current'
```

And repeat steps in previous comment
