### ISSUE TITLE
[Bug] Cannot install Git with Scoop/Shovel

### ISSUE THREAD

**Issue by TamamoNoMae13** [Ash258/scoop#282]
- **Branch**:  main
- **Powershell Version**:  5.1.19041.1320 and 7.2.2

## Bug Report

Moved from: https://github.com/ScoopInstaller/Scoop/issues/4864

#### Current Behavior

`scoop` refuses to install `git` and says "Scoop uses Git to update itself. Run 'scoop install git' and try again."

#### Expected Behavior

Scoop installing Git.

#### Additional context/output

Terminal output:
```
PS C:\Users\hung\scoop\apps\pwsh\current> scoop install git
ERROR Scoop uses Git to update itself. Run 'scoop install git' and try again.
```
I got a fork bomb issues like this issue: https://github.com/ScoopInstaller/Scoop/issues/4323, but with Git _version 2.35.1.windows.2_
I ran `scoop uninstall git` successfully but cannot `scoop install git`.

### System details

**Windows version:** 10 21H2

**OS architecture:** 64bit

**Comment by Ash258** [comment]
Use NEW branch se described in #279

**Comment by itpropro** [comment]
Any plans to release a new version to avoid the `NEW` branch workaround @Ash258?

**Comment by Ash258** [comment]
Not yet. After the war will end and when I have more time.

Use vanilla scoop if you want more active development.
