### ISSUE TITLE
Some kind of "verbose" or "debug" output is always printed 

### ISSUE THREAD

**Issue by riotrah** [Ash258/scoop#288]
- **Branch**: `main`
- **Powershell Version**: 7.3.0-preview.7

Hi! Firstly, thanks for this. Quite impressive. Some of your work should surely be in upstream, if it isn't already.

Secondly, I cannot tell if this problem is related instead only to base scoop, so if requested, I will also ask in that community.

**Problem**: I am receiving _tremendous_ amounts of noise from most scoop (shovel) commands. Worst of all are the commands that I think pertain to reading manifests: `list` `search` `info`.

There are 2 types of logging statements that I can tell:

1. For the list/search/etc commands, _per each item_ - appears to be a printing of hash-map/object entries like `[<key>, <value>] [<key2>, <value2>]`

eg:
```
$ scoop search zip

... hundreds of similar lines ...

[Name, zip-beta] [Print, versions/zip-beta] [Manifest, @{version=3.1d26; description=Zip compression utilities (beta version); homepage=http://infozip.sourceforge.net/; license=Info-ZIP; bin=System.Object[]; url=http://r.windows.random.supplies/zip3.1d26.zip; hash=822b1a808636e28d0c67e76572a21dc2bc1b2a1c092cc01c762c883e2c2cbd63; architecture=}] [Bucket, versions] [RequestedVersion, ] [Path, C:\Users\rayat\scoop\buckets\versions\bucket\zip-beta.json]
```

3. For various other ones - appears to be printing the underlying performed shell command, _in addition to printing the output of the actual command_ like `& "C:\WINDOWS\system32\cmd.exe" /d /c git -C ...`
   2. Interestingly, ihis doesn't happen for `scoop config FOO`

eg:
```
$ scoop --version

... several similar lines ...

'versions' bucket:
& "C:\WINDOWS\system32\cmd.exe" /d /c git -C "C:\Users\rayat\scoop\buckets\versions" --no-pager log --oneline --max-count=1 HEAD
```

This was not happening when I had base scoop, and happened after installing shovel. However, it's been a couple weeks since I've used my windows machine so perhaps something else changed that same day.

## screenshots if helpful:

1.
![image](https://user-images.githubusercontent.com/22646419/192125604-1d95be1c-fcd9-4d07-8280-871a6c5cc462.png)

2. 
![image](https://user-images.githubusercontent.com/22646419/192125594-ab99fd14-a0e1-4260-ade6-e6aa8bcec605.png)

## Env details:

1. I've set `scoop config debug` to false
2. Same for `$env:SCOOP_DEBUG`
3. I have not set anything for `PSDefaultParameterValues`

1. No proxy
2. Windows 11

Please let me know if you suspect any other env details would be useful for you.

Thanks again!

**Comment by Ash258** [comment]
Use `NEW` branch. The `main` is quite old and will stay that until war is over. Ideally switch back to original vanilla scoop.

Debug is enabled like this.

https://github.com/Ash258/Scoop-Core/blob/52fe1646d87ead40b642f112c3105c5aa54da3a5/lib/core.ps1#L326-L341

`shovel config rm debug; Remove-Item Env:\SCOOP_DEBUG`

![image](https://user-images.githubusercontent.com/13260377/192130983-662726a5-5d45-4dfe-90be-17a4ca09cf89.png)
