### ISSUE TITLE
Warning about missing IntelliJ-IDEA-Ultimate.json file in bucket

### ISSUE THREAD

**Issue by kmarcee** [Ash258/scoop#298]
- **Branch**: master
- **Powershell Version**: 5.1.22621.963
- **Scoop version**: v0.3.1 - Released at 2022-11-15
- **Bucket state**: 'JetBrains' bucket: f02f7c4a (HEAD -> main, origin/main, origin/HEAD) WebStorm-EAP: Update to version 2023.1-231.6471.14
- **Environment**: Nothing special. Latest Windows 11 Pro 22H2, build: 22621.1194

When running `scoop update *`, I get a warning complaining about a missing file. Actually, the file is there at the given location, but with a different extension, _yml_ instead of _json_.

Terminal output:
`WARN  error: Nem található a következő fájl: „C:\scoop\buckets\JetBrains\bucket\IntelliJ-IDEA-Ultimate.json”.`

That's in Hungarian. The same output in English it would be like:
`WARN  error: No such file/Cannot find file: „C:\scoop\buckets\JetBrains\bucket\IntelliJ-IDEA-Ultimate.json”.`

**Comment by Ash258** [comment]
Wrong repository. You are using vanilla Scoop. Scoop does not support yml typed manifests.

**Comment by kmarcee** [comment]
Hi Jakub,

Thank you for your extremely quick reply.
However, I cannot really step forward with that information. Your idea with overwriting the extension in the `install.json` could have been correct, but it still does not work.
Now I get the following error: `WARN  Error parsing JSON at C:\scoop\buckets\JetBrains\bucket\IntelliJ-IDEA-Ultimate.yml.`

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/1615792/216632781-8c0ec710-f242-468d-b79a-204094648ee5.png">

Actually, I don't really understand, how this works.
As you assumed, I use the "standard" Scoop (i.e. the "vanilla" version) - that's true, I also operate the things via _scoop_ commands, not _shovel_ commands - but the JetBrains bucket points to this repository (see screenshpot) and my IntelliJ IDEA is also installed from this bucket, I'm sure. I can imagine that is is a kind of mixture resulting in undefined behaviour, but it has been working until now more or less without errors. So I supposed that something had to be change recently...

If it's not the correct place to report this issue, could you please link me the right repository?
Initially, I wanted to go to the [main repo](https://github.com/ScoopInstaller/Scoop/issues/new?assignees=&labels=bug&template=Bug_report.md&title=%5BBug%5D+), but the hint `If your problem is related to a specific package, open the issue in the relevant bucket,
  not here.` redirected me to this repo.

Sorry for being puzzled about what to do. I hope you can help.

Best,
Marton

**Comment by Ash258** [comment]
Just do not use the JetBrains bucket. It will not work for Scoop users. Find other bucket that contains intalli-J idea.

**Comment by kmarcee** [comment]
Actually, I know that the `extras` bucket has [its version of IntelllliJ IDEA](https://github.com/ScoopInstaller/Extras/blob/master/bucket/idea-ultimate.json), too. Some time ago, I switched to the JetBrains bucket, as the vanilla version had issues with updates and this repo seemed more specific and reliable at the same time. :)
Another - even stronger reason - was that the [JetBrains Gateway](https://github.com/shovel-org/Windows-JetBrains-Bucket/blob/main/bucket/Gateway-EAP.yml) is not maintained there, which I also use and need nowadays.
So - after a quick googling - I don't really know, what other option I have...
Isn't there any explanation, what did suddenly go wrong, if it was working like a charm until now? Is it possible to fix it somehow (even by local workaround)?
