### ISSUE TITLE
gsudo always fails to update (or uninstall)

### ISSUE THREAD

**Issue by jeffrson** [Ash258/scoop#306]
- **Branch**: 

  "SCOOP_REPO": "https://github.com/Ash258/Scoop-Core",
  "SCOOP_BRANCH": "main",

- **Powershell Version**: 

7.4.1

The `gsudo` package always fails to update. This is the log:
```
Updating 'gsudo' (2.4.2 -> 2.4.4) [64bit]
Downloading new version
gsudo.setup.x64.msi (2,2 MB) [===] 100%
Checking hash of gsudo.setup.x64.msi ... ok.
Uninstalling 'gsudo' (2.4.2)
Removing shim for 'sudo'.
Unlinking ~\scoop\apps\gsudo\current
Uninstalling PowerShell module 'gsudoModule'.
Removing ~\scoop\modules\gsudoModule
ERROR Cannot bind argument to parameter 'LinkName' because it is an empty string.
```

Just `scoop update gsudo`. However, the same happens when I try to uninstall gsudo.

Looks like it cannot remove ~\scoop\modules\gsudoModule, which is a reparse point:
gci:
```
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
l-r--          09.01.2024    15:19                gsudoModule -> <USERPROFILE>\scoop\apps\gsudo\current
```
details shown by `fsutil reparsePoint query .\gsudoModule`. The destination "current" does not exist.

Currently I always need to remove the reparse point manually through fsutil, then delete the remaining folder. Finally gsudo can be updated.

https://github.com/ScoopInstaller/Main/issues/4788

**Comment by Ash258** [comment]
```
shovel config SCOOP_BRANCH NEW
shovel update
# Reinstall gsudo
```
